### ISSUE TITLE
rescale() doesn't work if sr > tr

### ISSUE THREAD

**Issue by mgeier** [melizalab/py-ewave#4]
```
import ewave
import numpy as np
ewave.rescale(np.array([32767], dtype='int16'), 'float32')
array([ 0.], dtype=float32)
```

The result should be 1.0 (or at least very close to it).
When // is replaced by /, this particular case works (but other cases may break).

**Comment by dmeliza** [comment]
Thanks for finding this. Switching to true division breaks some of the other conversions. I've never been happy with that function, so I'll see if I can find a better solution.

**Comment by mgeier** [comment]
Great, now it looks much better and it actually works (as far as I can tell).
I updated my description of ewave: http://nbviewer.ipython.org/github/mgeier/python-audio/blob/master/audio-files/audio-files-with-ewave.ipynb

It's very good that you created unit tests that now actually test the values, but they are not quite correct.
You should avoid functions that do "approximate" or "close" comparisons whenever possible.
In this concrete case, you should check for exact equality.
Then you would also find the bug in the tests: the value `1 - 1 / (1 << 31)` cannot be represented in `float32`, it will be altered to `1.0`.
You should use `float64` or a value that's actually representable by `float32`.
